"""Alembic migration environment."""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import engine_from_config, pool

from alembic import context

BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Importing the registry puts every table on the shared metadata, which is
# what autogenerate compares against the live database.
import app.models  # noqa: E402, F401
from app.shared.config import get_settings  # noqa: E402
from app.shared.db import Base  # noqa: E402

config = context.config

if config.config_file_name is not None:
    # Without this flag fileConfig disables every logger that the ini does
    # not declare, which silences the application when migrations run
    # in-process (the test suite, or a startup hook).
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# A caller (the test suite) may inject its own URL; only fall back to the
# application settings when it did not. Migrations always run as the schema
# owner, never as the runtime role.
if not config.get_main_option("sqlalchemy.url", None):
    config.set_main_option("sqlalchemy.url", str(get_settings().database_migration_url))

target_metadata = Base.metadata

# The PostGIS image puts `topology` and `tiger` on the database search_path and
# owns several tables in `public`. Neither belongs to this application's schema,
# so autogenerate must ignore them instead of proposing to drop them.
POSTGIS_OWNED_TABLES = frozenset(
    {
        "spatial_ref_sys",
        "geometry_columns",
        "geography_columns",
        "raster_columns",
        "raster_overviews",
    }
)


def include_object(
    obj: object,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: object,
) -> bool:
    """Keep PostGIS-owned objects out of autogenerated migrations."""
    return not (type_ == "table" and name in POSTGIS_OWNED_TABLES)


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting to the database."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    # Pin the search_path through the connection itself: the PostGIS image also
    # exposes `topology` and `tiger`, and reflecting them would make autogenerate
    # propose dropping them. Setting it with a statement instead would open an
    # implicit transaction and Alembic's own transaction would never commit.
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        connect_args={"options": "-csearch_path=public"},
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
