"""phase1: auth and users schema

Revision ID: c0004f4adba1
Revises: 
Create Date: 2026-09-23 09:26:24.675678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0004f4adba1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_category', sa.Enum('SECURITY', 'DOMAIN', 'SYSTEM', name='auditeventcategory', native_enum=False, length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='auditeventseverity', native_enum=False, length=16), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.Enum('PROPIETARIO', 'ADMIN_OPERACIONES', 'AGRONOMO', 'OPERADOR_DRONE', 'APLICADOR', 'BODEGUERO', 'JEFE_BODEGA', 'AUDITOR', 'APICULTOR', name='role', native_enum=False, length=32), nullable=True),
    sa.Column('actor_ip', postgresql.INET(), nullable=True),
    sa.Column('actor_user_agent', sa.String(length=512), nullable=True),
    sa.Column('target_resource_type', sa.String(length=64), nullable=True),
    sa.Column('target_resource_id', sa.Uuid(), nullable=True),
    sa.Column('predio_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILURE', 'DENIED', name='auditoutcome', native_enum=False, length=16), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('hash_prev', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_predio_id'), 'audit_log', ['predio_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)

    # audit_log is append-only: nobody may rewrite or erase history.
    # NOTE: this does not bind the table owner, who keeps every privilege.
    # The application should connect with a role that only holds INSERT/SELECT.
    op.execute("REVOKE UPDATE, DELETE ON audit_log FROM PUBLIC")

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_rut'), 'users', ['rut'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_predio_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('predio_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('PROPIETARIO', 'ADMIN_OPERACIONES', 'AGRONOMO', 'OPERADOR_DRONE', 'APLICADOR', 'BODEGUERO', 'JEFE_BODEGA', 'AUDITOR', 'APICULTOR', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'predio_id', 'role', name='uq_user_predio_roles_user_predio_role')
    )
    op.create_index(op.f('ix_user_predio_roles_predio_id'), 'user_predio_roles', ['predio_id'], unique=False)
    op.create_index(op.f('ix_user_predio_roles_user_id'), 'user_predio_roles', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('PROPIETARIO', 'ADMIN_OPERACIONES', 'AGRONOMO', 'OPERADOR_DRONE', 'APLICADOR', 'BODEGUERO', 'JEFE_BODEGA', 'AUDITOR', 'APICULTOR', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_two_factor',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.String(length=512), nullable=False),
    sa.Column('totp_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recovery_codes_hash', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###

    # --- audit_log immutability, see docs/decisions/ADR-002-audit-log-immutability.md ---
    # Layer 1: a trigger, which binds every role including the table owner.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_prevent_mutation()
        RETURNS TRIGGER
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log is append-only: % is not permitted', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update
            BEFORE UPDATE ON audit_log
            FOR EACH ROW
            EXECUTE FUNCTION audit_log_prevent_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_delete
            BEFORE DELETE ON audit_log
            FOR EACH ROW
            EXECUTE FUNCTION audit_log_prevent_mutation();
        """
    )
    # TRUNCATE does not fire row-level triggers.
    op.execute(
        """
        CREATE TRIGGER audit_log_no_truncate
            BEFORE TRUNCATE ON audit_log
            FOR EACH STATEMENT
            EXECUTE FUNCTION audit_log_prevent_mutation();
        """
    )

    # Layer 2: least privilege for the runtime role.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lar_app') THEN
                RAISE EXCEPTION
                    'Role lar_app is missing. Run scripts/init-db.sql first.';
            END IF;
        END
        $$;
        """
    )
    op.execute("GRANT INSERT, SELECT ON audit_log TO lar_app")
    op.execute(
        """
        GRANT SELECT, INSERT, UPDATE, DELETE
        ON users, user_roles, user_predio_roles, user_two_factor, refresh_tokens
        TO lar_app
        """
    )
    op.execute("GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO lar_app")

    # Future tables must not require a manual GRANT in every later phase.
    op.execute(
        """
        ALTER DEFAULT PRIVILEGES FOR ROLE lar_owner IN SCHEMA public
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lar_app
        """
    )
    op.execute(
        """
        ALTER DEFAULT PRIVILEGES FOR ROLE lar_owner IN SCHEMA public
            GRANT USAGE ON SEQUENCES TO lar_app
        """
    )
    # The default privileges above would otherwise hand audit_log back.
    op.execute("REVOKE UPDATE, DELETE ON audit_log FROM lar_app")



def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        ALTER DEFAULT PRIVILEGES FOR ROLE lar_owner IN SCHEMA public
            REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM lar_app
        """
    )
    op.execute(
        """
        ALTER DEFAULT PRIVILEGES FOR ROLE lar_owner IN SCHEMA public
            REVOKE USAGE ON SEQUENCES FROM lar_app
        """
    )
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_prevent_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_two_factor')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_predio_roles_user_id'), table_name='user_predio_roles')
    op.drop_index(op.f('ix_user_predio_roles_predio_id'), table_name='user_predio_roles')
    op.drop_table('user_predio_roles')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_rut'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_predio_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_correlation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
